image: node:22-alpine

create-pages:
  stage: deploy
  before_script:
    - corepack enable
  script:
    - pnpm install --frozen-lockfile
    - pnpm build
  pages:
    publish: dist
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
